service: ffmpeg-layer

provider:
  name: aws
  region: ap-southeast-2

layers:
  ffmpeg:
    path: layer

resources:
  Outputs:
    FfmpegLayerExport:
      Value:
        Ref: FfmpegLambdaLayer
      Export:
        Name: FfmpegLambdaLayer
